import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/app/components/Footer";
import Navbar from "@/app/components/Navbar";
import { workFontClass } from "@/lib/fonts.js";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main
          className={`${workFontClass} font-sans flex min-h-screen flex-col items-center bg-softBackgroundColor gap-6 py-12 px-6 mb-16`}
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
